In [141]:
from collections import deque
import pandas as pd
import os

In [142]:
project_dir = os.path.dirname(os.getcwd())
games = pd.read_csv(os.path.join(project_dir, "data/cleaned_chess.csv"))

In [143]:
games

,Site,Date,White,Black,Result,WhiteElo,BlackElo,ECO
0,Talcahuano CHI,2012-06-02,"Caceres Leal,Jaime","Farfan Ortiz,V",0.5,2137.0,2206.0,D13
1,Talcahuano CHI,2012-06-02,"Caceres Leal,Jaime","Salinas Herrera,P",0.0,2137.0,2409.0,A46
2,Talcahuano CHI,2012-06-02,"Farfan Ortiz,E","Vizama Riveros,C",0.0,2236.0,2256.0,C42
3,Talcahuano CHI,2012-06-02,"Rojas Sepulveda,E","Diaz Vasquez,M",0.5,2315.0,2212.0,A46
4,Talcahuano CHI,2012-06-02,"Estay Torreblanca,O","Alarcon,Rod",1.0,2214.0,2174.0,C17
...,...,...,...,...,...,...,...,...
3255651,Aktobe KAZ,2026-06-08,"Kabinazar,Nurmukhammed","Tarhan,Adar",0.5,2312.0,2482.0,B11
3255652,Aktobe KAZ,2026-06-08,"Zhalmakhanov,Ramazan","Kornienko,Konstantin",0.0,2478.0,2388.0,B28
3255653,Aktobe KAZ,2026-06-08,"Dronavalli,Harika","Degenbaev,Aziz",0.5,2466.0,2320.0,A06
3255654,Aktobe KAZ,2026-06-08,"Rozum,I","Makhnev,Denis",1.0,2455.0,2551.0,A40
3255655,Acqui Terme ITA,2026-06-08,"Parvulescu,Nicu","Breggia Bicchiere,Antonio",1.0,1768.0,1698.0,B12

Elo

In [144]:
games["EloDiff"] = games["WhiteElo"] - games["BlackElo"]
games["AvgElo"] = (games["WhiteElo"] + games["BlackElo"]) / 2
games["HigherRatedPlayer"] = games.loc[:,["WhiteElo", "BlackElo"]].idxmax(axis="columns").replace("BlackElo", 0).replace("WhiteElo", 1)
games

,Site,Date,White,Black,Result,WhiteElo,BlackElo,ECO,EloDiff,AvgElo,HigherRatedPlayer
0,Talcahuano CHI,2012-06-02,"Caceres Leal,Jaime","Farfan Ortiz,V",0.5,2137.0,2206.0,D13,-69.0,2171.5,0
1,Talcahuano CHI,2012-06-02,"Caceres Leal,Jaime","Salinas Herrera,P",0.0,2137.0,2409.0,A46,-272.0,2273.0,0
2,Talcahuano CHI,2012-06-02,"Farfan Ortiz,E","Vizama Riveros,C",0.0,2236.0,2256.0,C42,-20.0,2246.0,0
3,Talcahuano CHI,2012-06-02,"Rojas Sepulveda,E","Diaz Vasquez,M",0.5,2315.0,2212.0,A46,103.0,2263.5,1
4,Talcahuano CHI,2012-06-02,"Estay Torreblanca,O","Alarcon,Rod",1.0,2214.0,2174.0,C17,40.0,2194.0,1
...,...,...,...,...,...,...,...,...,...,...,...
3255651,Aktobe KAZ,2026-06-08,"Kabinazar,Nurmukhammed","Tarhan,Adar",0.5,2312.0,2482.0,B11,-170.0,2397.0,0
3255652,Aktobe KAZ,2026-06-08,"Zhalmakhanov,Ramazan","Kornienko,Konstantin",0.0,2478.0,2388.0,B28,90.0,2433.0,1
3255653,Aktobe KAZ,2026-06-08,"Dronavalli,Harika","Degenbaev,Aziz",0.5,2466.0,2320.0,A06,146.0,2393.0,1
3255654,Aktobe KAZ,2026-06-08,"Rozum,I","Makhnev,Denis",1.0,2455.0,2551.0,A40,-96.0,2503.0,0
3255655,Acqui Terme ITA,2026-06-08,"Parvulescu,Nicu","Breggia Bicchiere,Antonio",1.0,1768.0,1698.0,B12,70.0,1733.0,1

<h>Player History</h>
<p>New Features:</p>

In [145]:
player_stats = {}

WhiteGames = []
WhiteWin = []
WhiteLoss = []
WhiteDraw = []
BlackGames = []
BlackWin = []
BlackLoss = []
BlackDraw = []

WhiteWinRate = []
WhiteLossRate = []
WhiteDrawRate = []
BlackWinRate = []
BlackLossRate = []
BlackDrawRate = []

WLast10 = []
BLast10 = []

WasWGames = []
WasWWin = []
WasWLoss = []
WasWDraw = []
WasBGames = []
WasBWin = []
WasBLoss = []
WasBDraw = []
BasWGames = []
BasWWin = []
BasWLoss = []
BasWDraw = []
BasBGames = []
BasBWin = []
BasBLoss = []
BasBDraw = []

WasWWinRate = []
WasWLossRate = []
WasWDrawRate = []
WasBWinRate = []
WasBLossRate = []
WasBDrawRate = []
BasWWinRate = []
BasWLossRate = []
BasWDrawRate = []
BasBWinRate = []
BasBLossRate = []
BasBDrawRate = []

Storing the History:

In [146]:
def update_player(player, result, color):
    stats = player_stats.get(player)
    stats["games"] += 1
    if result == 1:
        if color == "white":
            stats["win"] += 1
            stats["whitegames"] += 1
            stats["whitewin"] += 1
            stats["last10"].append(result)
        else:
            stats["loss"] += 1
            stats["blackgames"] += 1
            stats["blackloss"] += 1
            stats["last10"].append(1 - result)
    elif result == 0.5:
        if color == "white":
            stats["draw"] += 1
            stats["whitegames"] += 1
            stats["whitedraw"] += 1
            stats["last10"].append(result)
        else:
            stats["draw"] += 1
            stats["blackgames"] += 1
            stats["blackdraw"] += 1
            stats["last10"].append(1 - result)
    else:
        if color == "white":
            stats["loss"] += 1
            stats["whitegames"] += 1
            stats["whiteloss"] += 1
            stats["last10"].append(result)
        else:
            stats["win"] += 1
            stats["blackgames"] += 1
            stats["blackwin"] += 1
            stats["last10"].append(1 - result)

In [147]:
for row in games.itertuples():
    white = row.White
    black = row.Black
    result = row.Result
    

    if white not in player_stats:
        player_stats[white] = {"games": 0, "win": 0, "loss": 0, "draw": 0, "whitegames": 0, "blackgames": 0, "whitewin": 0, "whiteloss": 0, "whitedraw": 0, "blackwin": 0, "blackloss": 0, "blackdraw": 0, "last10": deque([], maxlen=10)}
    if black not in player_stats:
        player_stats[black] = {"games": 0, "win": 0, "loss": 0, "draw": 0, "whitegames": 0, "blackgames": 0, "whitewin": 0, "whiteloss": 0, "whitedraw": 0, "blackwin": 0, "blackloss": 0, "blackdraw": 0, "last10": deque([], maxlen=10)}


    white_stats = player_stats.get(white)
    black_stats = player_stats.get(black)

    WhiteGames.append(white_stats["games"])
    WhiteWin.append(white_stats["win"])
    WhiteLoss.append(white_stats["loss"])
    WhiteDraw.append(white_stats["draw"])
    BlackGames.append(black_stats["games"])
    BlackWin.append(black_stats["win"])
    BlackLoss.append(black_stats["loss"])
    BlackDraw.append(black_stats["draw"])
    WasWGames.append(white_stats["whitegames"])
    WasWWin.append(white_stats["whitewin"])
    WasWLoss.append(white_stats["whiteloss"])
    WasWDraw.append(white_stats["whitedraw"])
    WasBGames.append(white_stats["blackgames"])
    WasBWin.append(white_stats["blackwin"])
    WasBLoss.append(white_stats["blackloss"])
    WasBDraw.append(white_stats["blackdraw"])
    BasWGames.append(black_stats["whitegames"])
    BasWWin.append(black_stats["whitewin"])
    BasWLoss.append(black_stats["whiteloss"])
    BasWDraw.append(black_stats["whitedraw"])
    BasBGames.append(black_stats["blackgames"])
    BasBWin.append(black_stats["blackwin"])
    BasBLoss.append(black_stats["blackloss"])
    BasBDraw.append(black_stats["blackdraw"])


    if white_stats["games"]:
        WhiteWinRate.append(white_stats["win"] / white_stats["games"])
        WhiteLossRate.append(white_stats["loss"] / white_stats["games"])
        WhiteDrawRate.append(white_stats["draw"] / white_stats["games"])
    else:
        WhiteWinRate.append(0)
        WhiteLossRate.append(0)
        WhiteDrawRate.append(0)
        
    if black_stats["games"]:
        BlackWinRate.append(black_stats["win"] / black_stats["games"])
        BlackLossRate.append(black_stats["loss"] / black_stats["games"])
        BlackDrawRate.append(black_stats["draw"] / black_stats["games"])
    else:
        BlackWinRate.append(0)
        BlackLossRate.append(0)
        BlackDrawRate.append(0)

    if white_stats["whitegames"]:
        WasWWinRate.append(white_stats["whitewin"] / white_stats["whitegames"])
        WasWLossRate.append(white_stats["whiteloss"] / white_stats["whitegames"])
        WasWDrawRate.append(white_stats["whitedraw"] / white_stats["whitegames"])
    else:
        WasWWinRate.append(0)
        WasWLossRate.append(0)
        WasWDrawRate.append(0)

    if white_stats["blackgames"]:
        WasBWinRate.append(white_stats["blackwin"] / white_stats["blackgames"])
        WasBLossRate.append(white_stats["blackloss"] / white_stats["blackgames"])
        WasBDrawRate.append(white_stats["blackdraw"] / white_stats["blackgames"])
    else:
        WasBWinRate.append(0)
        WasBLossRate.append(0)
        WasBDrawRate.append(0)

    if black_stats["whitegames"]:
        BasWWinRate.append(black_stats["whitewin"] / black_stats["whitegames"])
        BasWLossRate.append(black_stats["whiteloss"] / black_stats["whitegames"])
        BasWDrawRate.append(black_stats["whitedraw"] / black_stats["whitegames"])
    else:
        BasWWinRate.append(0)
        BasWLossRate.append(0)
        BasWDrawRate.append(0)

    if black_stats["blackgames"]:
        BasBWinRate.append(black_stats["blackwin"] / black_stats["blackgames"])
        BasBLossRate.append(black_stats["blackloss"] / black_stats["blackgames"])
        BasBDrawRate.append(black_stats["blackdraw"] / black_stats["blackgames"])
    else:
        BasBWinRate.append(0)
        BasBLossRate.append(0)
        BasBDrawRate.append(0)
    
    if white_stats["last10"]:
        WLast10.append(sum(white_stats["last10"]) / len(white_stats["last10"]))
    else:
        WLast10.append(0)
    if black_stats["last10"]:
        BLast10.append(sum(black_stats["last10"]) / len(black_stats["last10"]))
    else:
        BLast10.append(0)
    

    ###updating the features
    update_player(white, result, "white")
    update_player(black, result, "black")

    
    print(white_stats)
    print(black_stats)
    print(row)
    break

{'games': 1, 'win': 0, 'loss': 0, 'draw': 1, 'whitegames': 1, 'blackgames': 0, 'whitewin': 0, 'whiteloss': 0, 'whitedraw': 1, 'blackwin': 0, 'blackloss': 0, 'blackdraw': 0, 'last10': deque([0.5], maxlen=10)}
{'games': 1, 'win': 0, 'loss': 0, 'draw': 1, 'whitegames': 0, 'blackgames': 1, 'whitewin': 0, 'whiteloss': 0, 'whitedraw': 0, 'blackwin': 0, 'blackloss': 0, 'blackdraw': 1, 'last10': deque([0.5], maxlen=10)}
Pandas(Index=0, Site='Talcahuano CHI', Date='2012-06-02', White='Caceres Leal,Jaime', Black='Farfan Ortiz,V', Result=0.5, WhiteElo=2137.0, BlackElo=2206.0, ECO='D13', EloDiff=-69.0, AvgElo=2171.5, HigherRatedPlayer=0)

Head2Head Statistics

New Features:

In [148]:
head2head = {}

h2h_games = []
h2h_Player1Win = []
h2h_Player2Win = []
h2h_Draw = []
h2h_Player1WinRate = []
h2h_Player2WinRate = []
h2h_Drawrate = []
h2h_last5 = []

Keeping track of H2H:

In [149]:
def update_h2h(pair, result, white, black):
    stats = head2head.get(pair)
    stats["games"] += 1
    stats["last5"].append(result)

    if result == 1:
        stats[white] += 1
    elif result == 0.5:
        stats["draw"] += 1
    else:
        stats[black] += 1

In [150]:
for row in games.itertuples():
    white = row.White
    black = row.Black
    result = row.Result
    pair = tuple(sorted((white, black)))

    if pair not in head2head:
        head2head[pair] = {"games": 0, pair[0]: 0, pair[1]: 0, "draw": 0, "last5": deque([], maxlen=5)}
    
    pair_stats = head2head[pair]

    h2h_games.append(pair_stats["games"])
    h2h_Player1Win.append(pair_stats[pair[0]])
    h2h_Player2Win.append(pair_stats[pair[1]])
    h2h_Draw.append(pair_stats["draw"])
    
    if pair_stats["games"]:
        h2h_Player1WinRate.append(pair_stats[pair[0]] / pair_stats["games"])
        h2h_Player2WinRate.append(pair_stats[pair[1]] / pair_stats["games"])
        h2h_Drawrate.append(pair_stats["draw"] / pair_stats["games"])
        h2h_last5.append(sum(pair_stats["last5"]) / len(pair_stats["last5"]))
    else:
        h2h_Player1WinRate.append(0)
        h2h_Player2WinRate.append(0)
        h2h_Drawrate.append(0)
        h2h_last5.append(0)

    ###updating the h2h features
    update_h2h(pair, result, white, black)

    print(head2head)
    break

{('Caceres Leal,Jaime', 'Farfan Ortiz,V'): {'games': 1, 'Caceres Leal,Jaime': 0, 'Farfan Ortiz,V': 0, 'draw': 1, 'last5': deque([0.5], maxlen=5)}}

Diff

New Features:

In [151]:
Last10Diff = []
GamesDiff = []
WinDiff = []
WinRateDiff = []
h2h_WinDiff = []
h2h_WinRateDiff = []

Calculating the Diff stats:

In [152]:
for i in range(len(games)):
    Last10Diff.append(WLast10[i] - BLast10[i])
    GamesDiff.append(WhiteGames[i] - BlackGames[i])
    WinDiff.append(WhiteWin[i] - BlackWin[i])
    WinRateDiff.append(WhiteWinRate[i] - BlackWinRate[i])
    h2h_WinDiff.append(h2h_Player1Win[i] - h2h_Player2Win[i])
    h2h_WinRateDiff.append(h2h_Player1WinRate[i] - h2h_Player2WinRate[i])
    print(h2h_WinDiff)
    break

[0]

ECO Stats(opening stats)

New Features:

In [153]:
ECOs = {}

ECO_Games = []
ECO_WhiteWin = []
ECO_BlackWin = []
ECO_Draw = []
ECO_WhiteWinRate = []
ECO_BlackWinRate = []
ECO_DrawRate = []

In [154]:
def update_eco(eco, result):
    stats = ECOs[eco]
    stats["games"] += 1
    if result == 1:
        stats["whitewin"] += 1
    elif result == 0.5:
        stats["draw"] += 1
    else:
        stats["blackwin"] += 1

In [155]:
count = 0
for row in games.itertuples():
    result = row.Result
    eco = row.ECO

    if eco not in ECOs:
        ECOs[eco] = {"games": 0, "whitewin": 0, "blackwin": 0, "draw": 0}
    eco_stats = ECOs[eco]
    
    ECO_Games.append(eco_stats["games"])
    ECO_WhiteWin.append(eco_stats["whitewin"])
    ECO_BlackWin.append(eco_stats["blackwin"])
    ECO_Draw.append(eco_stats["draw"])
    if eco_stats["games"]:
        ECO_WhiteWinRate.append(eco_stats["whitewin"] / eco_stats["games"])
        ECO_BlackWinRate.append(eco_stats["blackwin"] / eco_stats["games"])
        ECO_DrawRate.append(eco_stats["draw"] / eco_stats["games"])
    else:
        ECO_WhiteWinRate.append(0)
        ECO_BlackWinRate.append(0)
        ECO_DrawRate.append(0)
    
    ###updating features
    update_eco(eco, result)

    if count>1000:   
        print(ECOs)
        break
    count+=1

{'D13': {'games': 4, 'whitewin': 1, 'blackwin': 0, 'draw': 3}, 'A46': {'games': 11, 'whitewin': 4, 'blackwin': 3, 'draw': 4}, 'C42': {'games': 4, 'whitewin': 1, 'blackwin': 2, 'draw': 1}, 'C17': {'games': 4, 'whitewin': 2, 'blackwin': 2, 'draw': 0}, 'D45': {'games': 11, 'whitewin': 2, 'blackwin': 3, 'draw': 6}, 'E61': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'A57': {'games': 3, 'whitewin': 2, 'blackwin': 0, 'draw': 1}, 'B30': {'games': 16, 'whitewin': 3, 'blackwin': 6, 'draw': 7}, 'D79': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'B32': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'A56': {'games': 6, 'whitewin': 5, 'blackwin': 0, 'draw': 1}, 'B44': {'games': 2, 'whitewin': 2, 'blackwin': 0, 'draw': 0}, 'B45': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'B12': {'games': 19, 'whitewin': 7, 'blackwin': 5, 'draw': 7}, 'C41': {'games': 5, 'whitewin': 2, 'blackwin': 2, 'draw': 1}, 'A05': {'games': 5, 'whitewin': 3, 'blackwin': 0, 'draw': 2}, 'D37': {'games': 9, 'whitewin': 5, 'blackwin': 2, 'draw': 2}, 'E53': {'games': 2, 'whitewin': 2, 'blackwin': 0, 'draw': 0}, 'D47': {'games': 4, 'whitewin': 3, 'blackwin': 1, 'draw': 0}, 'B92': {'games': 7, 'whitewin': 0, 'blackwin': 5, 'draw': 2}, 'E84': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'A16': {'games': 4, 'whitewin': 2, 'blackwin': 0, 'draw': 2}, 'D83': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B81': {'games': 3, 'whitewin': 1, 'blackwin': 2, 'draw': 0}, 'D71': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E81': {'games': 5, 'whitewin': 1, 'blackwin': 3, 'draw': 1}, 'E54': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'B13': {'games': 5, 'whitewin': 0, 'blackwin': 3, 'draw': 2}, 'B31': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B90': {'games': 11, 'whitewin': 7, 'blackwin': 2, 'draw': 2}, 'E40': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B23': {'games': 10, 'whitewin': 4, 'blackwin': 4, 'draw': 2}, 'A13': {'games': 4, 'whitewin': 0, 'blackwin': 2, 'draw': 2}, 'E21': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'A07': {'games': 6, 'whitewin': 3, 'blackwin': 1, 'draw': 2}, 'D17': {'games': 4, 'whitewin': 2, 'blackwin': 0, 'draw': 2}, 'C15': {'games': 3, 'whitewin': 3, 'blackwin': 0, 'draw': 0}, 'A80': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'A83': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'D30': {'games': 7, 'whitewin': 3, 'blackwin': 3, 'draw': 1}, 'B08': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'D02': {'games': 7, 'whitewin': 3, 'blackwin': 4, 'draw': 0}, 'E32': {'games': 14, 'whitewin': 5, 'blackwin': 3, 'draw': 6}, 'B09': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'E46': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'C67': {'games': 6, 'whitewin': 2, 'blackwin': 2, 'draw': 2}, 'E70': {'games': 5, 'whitewin': 1, 'blackwin': 2, 'draw': 2}, 'E06': {'games': 5, 'whitewin': 3, 'blackwin': 2, 'draw': 0}, 'D70': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'C05': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'D35': {'games': 7, 'whitewin': 4, 'blackwin': 2, 'draw': 1}, 'A09': {'games': 4, 'whitewin': 1, 'blackwin': 1, 'draw': 2}, 'B50': {'games': 7, 'whitewin': 4, 'blackwin': 1, 'draw': 2}, 'A11': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'D11': {'games': 16, 'whitewin': 7, 'blackwin': 4, 'draw': 5}, 'B78': {'games': 2, 'whitewin': 2, 'blackwin': 0, 'draw': 0}, 'C88': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'A37': {'games': 3, 'whitewin': 2, 'blackwin': 0, 'draw': 1}, 'A20': {'games': 8, 'whitewin': 4, 'blackwin': 3, 'draw': 1}, 'B21': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B84': {'games': 5, 'whitewin': 1, 'blackwin': 1, 'draw': 3}, 'D32': {'games': 2, 'whitewin': 2, 'blackwin': 0, 'draw': 0}, 'C65': {'games': 3, 'whitewin': 3, 'blackwin': 0, 'draw': 0}, 'B40': {'games': 16, 'whitewin': 9, 'blackwin': 2, 'draw': 5}, 'A35': {'games': 4, 'whitewin': 2, 'blackwin': 1, 'draw': 1}, 'A40': {'games': 6, 'whitewin': 1, 'blackwin': 3, 'draw': 2}, 'E13': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'D38': {'games': 3, 'whitewin': 2, 'blackwin': 0, 'draw': 1}, 'C00': {'games': 10, 'whitewin': 5, 'blackwin': 2, 'draw': 3}, 'D85': {'games': 4, 'whitewin': 3, 'blackwin': 0, 'draw': 1}, 'B22': {'games': 19, 'whitewin': 7, 'blackwin': 8, 'draw': 4}, 'C86': {'games': 3, 'whitewin': 1, 'blackwin': 0, 'draw': 2}, 'E10': {'games': 5, 'whitewin': 1, 'blackwin': 2, 'draw': 2}, 'D00': {'games': 4, 'whitewin': 3, 'blackwin': 1, 'draw': 0}, 'E00': {'games': 6, 'whitewin': 2, 'blackwin': 3, 'draw': 1}, 'B43': {'games': 5, 'whitewin': 2, 'blackwin': 2, 'draw': 1}, 'A61': {'games': 5, 'whitewin': 1, 'blackwin': 3, 'draw': 1}, 'D31': {'games': 11, 'whitewin': 6, 'blackwin': 0, 'draw': 5}, 'A48': {'games': 8, 'whitewin': 2, 'blackwin': 5, 'draw': 1}, 'E62': {'games': 7, 'whitewin': 2, 'blackwin': 1, 'draw': 4}, 'E20': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'C22': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'D15': {'games': 4, 'whitewin': 3, 'blackwin': 1, 'draw': 0}, 'C11': {'games': 8, 'whitewin': 4, 'blackwin': 2, 'draw': 2}, 'C63': {'games': 4, 'whitewin': 3, 'blackwin': 0, 'draw': 1}, 'D60': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'B01': {'games': 19, 'whitewin': 8, 'blackwin': 6, 'draw': 5}, 'B11': {'games': 7, 'whitewin': 4, 'blackwin': 1, 'draw': 2}, 'A59': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'B04': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'A87': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'A21': {'games': 4, 'whitewin': 3, 'blackwin': 1, 'draw': 0}, 'C99': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'B28': {'games': 3, 'whitewin': 0, 'blackwin': 1, 'draw': 2}, 'A67': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'A14': {'games': 7, 'whitewin': 3, 'blackwin': 1, 'draw': 3}, 'B18': {'games': 5, 'whitewin': 1, 'blackwin': 1, 'draw': 3}, 'E94': {'games': 6, 'whitewin': 3, 'blackwin': 1, 'draw': 2}, 'A65': {'games': 4, 'whitewin': 2, 'blackwin': 0, 'draw': 2}, 'C90': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'D16': {'games': 4, 'whitewin': 1, 'blackwin': 2, 'draw': 1}, 'A01': {'games': 2, 'whitewin': 2, 'blackwin': 0, 'draw': 0}, 'B27': {'games': 4, 'whitewin': 0, 'blackwin': 2, 'draw': 2}, 'E04': {'games': 5, 'whitewin': 2, 'blackwin': 1, 'draw': 2}, 'A50': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'B06': {'games': 13, 'whitewin': 6, 'blackwin': 7, 'draw': 0}, 'B10': {'games': 5, 'whitewin': 3, 'blackwin': 1, 'draw': 1}, 'B93': {'games': 3, 'whitewin': 0, 'blackwin': 1, 'draw': 2}, 'A41': {'games': 9, 'whitewin': 6, 'blackwin': 2, 'draw': 1}, 'A15': {'games': 16, 'whitewin': 3, 'blackwin': 6, 'draw': 7}, 'D05': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'B03': {'games': 4, 'whitewin': 3, 'blackwin': 1, 'draw': 0}, 'D20': {'games': 5, 'whitewin': 3, 'blackwin': 0, 'draw': 2}, 'E71': {'games': 5, 'whitewin': 1, 'blackwin': 3, 'draw': 1}, 'A25': {'games': 3, 'whitewin': 1, 'blackwin': 0, 'draw': 2}, 'E59': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'C53': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'C84': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'Unknown': {'games': 4, 'whitewin': 1, 'blackwin': 1, 'draw': 2}, 'C70': {'games': 4, 'whitewin': 1, 'blackwin': 1, 'draw': 2}, 'E72': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'D52': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'B34': {'games': 6, 'whitewin': 1, 'blackwin': 2, 'draw': 3}, 'A04': {'games': 9, 'whitewin': 7, 'blackwin': 1, 'draw': 1}, 'E12': {'games': 6, 'whitewin': 2, 'blackwin': 1, 'draw': 3}, 'E30': {'games': 2, 'whitewin': 2, 'blackwin': 0, 'draw': 0}, 'A00': {'games': 18, 'whitewin': 9, 'blackwin': 3, 'draw': 6}, 'A89': {'games': 3, 'whitewin': 2, 'blackwin': 0, 'draw': 1}, 'D12': {'games': 4, 'whitewin': 0, 'blackwin': 2, 'draw': 2}, 'D43': {'games': 4, 'whitewin': 1, 'blackwin': 2, 'draw': 1}, 'B19': {'games': 3, 'whitewin': 2, 'blackwin': 1, 'draw': 0}, 'B83': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'A45': {'games': 8, 'whitewin': 3, 'blackwin': 3, 'draw': 2}, 'C45': {'games': 8, 'whitewin': 4, 'blackwin': 1, 'draw': 3}, 'E76': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C96': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'B16': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'D81': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C92': {'games': 4, 'whitewin': 2, 'blackwin': 0, 'draw': 2}, 'D48': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B76': {'games': 6, 'whitewin': 3, 'blackwin': 0, 'draw': 3}, 'E16': {'games': 3, 'whitewin': 1, 'blackwin': 0, 'draw': 2}, 'C80': {'games': 3, 'whitewin': 0, 'blackwin': 1, 'draw': 2}, 'A17': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'E11': {'games': 7, 'whitewin': 4, 'blackwin': 1, 'draw': 2}, 'E77': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'E63': {'games': 3, 'whitewin': 3, 'blackwin': 0, 'draw': 0}, 'C76': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C02': {'games': 4, 'whitewin': 0, 'blackwin': 4, 'draw': 0}, 'A30': {'games': 4, 'whitewin': 2, 'blackwin': 0, 'draw': 2}, 'C55': {'games': 3, 'whitewin': 2, 'blackwin': 1, 'draw': 0}, 'B07': {'games': 7, 'whitewin': 2, 'blackwin': 3, 'draw': 2}, 'B29': {'games': 3, 'whitewin': 0, 'blackwin': 0, 'draw': 3}, 'B14': {'games': 5, 'whitewin': 2, 'blackwin': 3, 'draw': 0}, 'E07': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'A08': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'D34': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'B52': {'games': 5, 'whitewin': 1, 'blackwin': 1, 'draw': 3}, 'A28': {'games': 4, 'whitewin': 1, 'blackwin': 2, 'draw': 1}, 'B42': {'games': 6, 'whitewin': 3, 'blackwin': 2, 'draw': 1}, 'C44': {'games': 7, 'whitewin': 3, 'blackwin': 2, 'draw': 2}, 'D19': {'games': 6, 'whitewin': 2, 'blackwin': 1, 'draw': 3}, 'E91': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'B00': {'games': 9, 'whitewin': 3, 'blackwin': 4, 'draw': 2}, 'B80': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'B51': {'games': 3, 'whitewin': 0, 'blackwin': 3, 'draw': 0}, 'E92': {'games': 7, 'whitewin': 4, 'blackwin': 3, 'draw': 0}, 'C78': {'games': 4, 'whitewin': 1, 'blackwin': 1, 'draw': 2}, 'C04': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'D94': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'C60': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'E01': {'games': 2, 'whitewin': 2, 'blackwin': 0, 'draw': 0}, 'B86': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'C71': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'D10': {'games': 5, 'whitewin': 2, 'blackwin': 0, 'draw': 3}, 'C03': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'E82': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'B35': {'games': 4, 'whitewin': 1, 'blackwin': 3, 'draw': 0}, 'B49': {'games': 4, 'whitewin': 2, 'blackwin': 1, 'draw': 1}, 'C16': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'C18': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'E42': {'games': 3, 'whitewin': 2, 'blackwin': 0, 'draw': 1}, 'B05': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B47': {'games': 6, 'whitewin': 0, 'blackwin': 2, 'draw': 4}, 'E87': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'C85': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'E68': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'E35': {'games': 3, 'whitewin': 0, 'blackwin': 0, 'draw': 3}, 'D86': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'D44': {'games': 3, 'whitewin': 2, 'blackwin': 1, 'draw': 0}, 'B41': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'A53': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B63': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'B54': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E67': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E48': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'B20': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'E25': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E79': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E60': {'games': 6, 'whitewin': 4, 'blackwin': 0, 'draw': 2}, 'A81': {'games': 3, 'whitewin': 2, 'blackwin': 0, 'draw': 1}, 'C13': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'B17': {'games': 4, 'whitewin': 1, 'blackwin': 1, 'draw': 2}, 'A22': {'games': 4, 'whitewin': 1, 'blackwin': 1, 'draw': 2}, 'D01': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'B57': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'C01': {'games': 2, 'whitewin': 0, 'blackwin': 2, 'draw': 0}, 'A03': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'D77': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'C74': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'A49': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'E97': {'games': 4, 'whitewin': 3, 'blackwin': 0, 'draw': 1}, 'A55': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'D80': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'E29': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'B53': {'games': 5, 'whitewin': 1, 'blackwin': 1, 'draw': 3}, 'E47': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'A42': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'A69': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'E38': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'B33': {'games': 3, 'whitewin': 0, 'blackwin': 0, 'draw': 3}, 'C06': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'A10': {'games': 4, 'whitewin': 1, 'blackwin': 1, 'draw': 2}, 'B36': {'games': 2, 'whitewin': 0, 'blackwin': 0, 'draw': 2}, 'C07': {'games': 4, 'whitewin': 1, 'blackwin': 1, 'draw': 2}, 'C10': {'games': 2, 'whitewin': 0, 'blackwin': 0, 'draw': 2}, 'A58': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C77': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'C69': {'games': 3, 'whitewin': 0, 'blackwin': 2, 'draw': 1}, 'A43': {'games': 3, 'whitewin': 2, 'blackwin': 1, 'draw': 0}, 'D23': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B24': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'D93': {'games': 2, 'whitewin': 1, 'blackwin': 0, 'draw': 1}, 'C58': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'D51': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B67': {'games': 3, 'whitewin': 2, 'blackwin': 1, 'draw': 0}, 'B48': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'A18': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'E95': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'D41': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'D21': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B98': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'D07': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'A47': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'A29': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C56': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'A39': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'D26': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B96': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E73': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C12': {'games': 3, 'whitewin': 1, 'blackwin': 1, 'draw': 1}, 'B65': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C50': {'games': 2, 'whitewin': 2, 'blackwin': 0, 'draw': 0}, 'E93': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E43': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'E17': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'E09': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'E90': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'D90': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'D55': {'games': 2, 'whitewin': 0, 'blackwin': 1, 'draw': 1}, 'D14': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'B82': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E86': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'D03': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'B38': {'games': 3, 'whitewin': 2, 'blackwin': 0, 'draw': 1}, 'E56': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C82': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'B66': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'C47': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'A02': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'E15': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'C36': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'D04': {'games': 2, 'whitewin': 1, 'blackwin': 1, 'draw': 0}, 'E34': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'D53': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'E80': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}, 'D24': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C25': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'C72': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'D87': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'B26': {'games': 1, 'whitewin': 1, 'blackwin': 0, 'draw': 0}, 'D72': {'games': 1, 'whitewin': 0, 'blackwin': 0, 'draw': 1}, 'C91': {'games': 1, 'whitewin': 0, 'blackwin': 1, 'draw': 0}}