In [2]:
import pandas as pd
import glob
import os

In [3]:
project_dir = os.path.dirname(os.getcwd())

In [4]:
all_files = glob.glob(os.path.join(project_dir, "data/raw_data/games_20*.csv"))
all_files = sorted(all_files)

Combining all games

In [5]:
all_month_df = []
for file in all_files:
    df_month = pd.read_csv(file)
    all_month_df.append(df_month)

games = pd.concat(all_month_df, ignore_index=True)

Handling duplicate rows and nan

In [6]:

games = games.drop_duplicates()
games["ECO"] = games["ECO"].fillna("Unknown")
games["Opening"] = games["Opening"].fillna("Unknown")
games["Moves"] = games["Moves"].fillna("Unknown")
games.dropna(inplace=True, ignore_index=True)
print(games.isna().sum())
print(len(games))

Event       0
Site        0
Date        0
White       0
Black       0
Result      0
WhiteElo    0
BlackElo    0
ECO         0
Opening     0
Moves       0
dtype: int64
3260183

Exploring the games

In [7]:
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 3260183 entries, 0 to 3260182
Data columns (total 11 columns):
 #   Column    Dtype
---  ------    -----
 0   Event     str
 1   Site      str
 2   Date      str
 3   White     str
 4   Black     str
 5   Result    str
 6   WhiteElo  float64
 7   BlackElo  float64
 8   ECO       str
 9   Opening   str
 10  Moves     str
dtypes: float64(2), str(9)
memory usage: 273.6 MB

In [8]:
games.describe()

           WhiteElo      BlackElo
count  3.260183e+06  3.260183e+06
mean   2.248658e+03  2.245490e+03
std    2.779910e+02  3.004536e+02
min    1.001000e+03  1.001000e+03
25%    2.093000e+03  2.089000e+03
50%    2.279000e+03  2.276000e+03
75%    2.436000e+03  2.434000e+03
max    3.958000e+03  2.042690e+05

In [9]:
print(games.loc[games["BlackElo"].idxmax()])
print(games.loc[games["WhiteElo"].idxmax()])

Event                                         TCh-BEL 2014-15
Site                                              Belgium BEL
Date                                               2014.09.28
White                                               Claesen,P
Black                                              Decoster,F
Result                                                1/2-1/2
WhiteElo                                               2327.0
BlackElo                                             204269.0
ECO                                                       B20
Opening                                      Sicilian defence
Moves       1. e4 c5 2. c4 Nc6 3. Nc3 e6 4. g3 g6 5. Bg2 B...
Name: 294391, dtype: object
Event                                    TCEC 20 Premier 2020
Site                                       tcec-chess.com INT
Date                                               2020.03.30
White                                LCZero v0.24-sv-t60-3010
Black                                       ScorpioNN 3.0.7.1
Result                                                    1-0
WhiteElo                                               3958.0
BlackElo                                               3812.0
ECO                                                       B12
Opening                                             Caro-Kann
Moves       1. e4 c6 2. d4 d5 3. e5 Bf5 4. h4 h6 5. g4 Bd7...
Name: 1162875, dtype: object

In [10]:
print(games["BlackElo"].value_counts().sort_index().tail(20))
games["WhiteElo"].value_counts().sort_index().tail(20)

BlackElo
3746.0       4
3749.0      78
3752.0      18
3761.0      21
3763.0      50
3794.0       8
3796.0      49
3807.0      50
3809.0      39
3810.0      18
3812.0      18
3815.0      11
3840.0       8
3846.0      18
3851.0       5
3854.0      18
3912.0      18
3936.0      36
3958.0      18
204269.0     1
Name: count, dtype: int64

WhiteElo
3743.0    21
3746.0     5
3749.0    78
3752.0    18
3761.0    21
3763.0    50
3794.0     8
3796.0    49
3807.0    50
3809.0    39
3810.0    18
3812.0    18
3815.0    11
3840.0    10
3846.0    18
3851.0     8
3854.0    18
3912.0    18
3936.0    36
3958.0    18
Name: count, dtype: int64

In [11]:
games.sort_values("BlackElo",ascending=False).head(10)

,Event,Site,Date,White,Black,Result,WhiteElo,BlackElo,ECO,Opening,Moves
294391,TCh-BEL 2014-15,Belgium BEL,2014.09.28,"Claesen,P","Decoster,F",1/2-1/2,2327.0,204269.0,B20,Sicilian defence,1. e4 c5 2. c4 Nc6 3. Nc3 e6 4. g3 g6 5. Bg2 B...
1162999,TCEC 20 Premier 2020,tcec-chess.com INT,2020.03.30,Ethereal 12.01,LCZero v0.24-sv-t60-3010,1/2-1/2,3810.0,3958.0,B57,Sicilian,1. e4 c5 2. Nf3 Nc6 3. d4 cxd4 4. Nxd4 Nf6 5. ...
1162980,TCEC 20 Premier 2020,tcec-chess.com INT,2020.03.27,Stockfish 202003092246,LCZero v0.24-sv-t60-3010,1/2-1/2,3936.0,3958.0,B03,Alekhine's defence,1. e4 Nf6 2. e5 Nd5 3. d4 d6 4. c4 Nb6 5. f4 B...
1162974,TCEC 20 Premier 2020,tcec-chess.com INT,2020.03.27,ScorpioNN 3.0.7.1,LCZero v0.24-sv-t60-3010,1/2-1/2,3812.0,3958.0,B12,Caro-Kann,1. e4 c6 2. d4 d5 3. e5 Bf5 4. h4 h6 5. g4 Bd7...
1162973,TCEC 20 Premier 2020,tcec-chess.com INT,2020.03.27,AllieStein v0.5_timefix-n14.0,LCZero v0.24-sv-t60-3010,1/2-1/2,3936.0,3958.0,B90,Sicilian,1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. N...
1162966,TCEC 20 Premier 2020,tcec-chess.com INT,2020.03.26,KomodoMCTS 2503.05,LCZero v0.24-sv-t60-3010,1/2-1/2,3809.0,3958.0,A20,English opening,1. c4 e5 2. g3 Nf6 3. Bg2 g6 4. Nc3 Bg7 5. d3 ...
1170267,TCEC 20 Premier 2020,tcec-chess.com INT,2020.04.08,Komodo 2503.05,LCZero v0.24-sv-t60-3010,1-0,3912.0,3958.0,E90,King's Indian,1. d4 Nf6 2. c4 g6 3. Nc3 Bg7 4. e4 d6 5. Nf3 ...
1162958,TCEC 20 Premier 2020,tcec-chess.com INT,2020.03.25,Houdini 6.03,LCZero v0.24-sv-t60-3010,1/2-1/2,3854.0,3958.0,A14,English,1. g3 e6 2. Bg2 d5 3. Nf3 Nf6 4. O-O Be7 5. c4...
1170409,TCEC 20 Premier 2020,tcec-chess.com INT,2020.04.01,Komodo 2503.05,LCZero v0.24-sv-t60-3010,1/2-1/2,3912.0,3958.0,B51,Sicilian,1. e4 c5 2. Nf3 d6 3. Bb5+ Nc6 4. O-O Bd7 5. R...
1170413,TCEC 20 Premier 2020,tcec-chess.com INT,2020.04.01,Houdini 6.03,LCZero v0.24-sv-t60-3010,1/2-1/2,3854.0,3958.0,A16,English opening,1. c4 Nf6 2. Nc3 g6 3. d3 d6 4. e4 Bg7 5. Nge2...

<h>Removing abnormally elo rated rows</h>
    <p>The elo > 3000 seems like the elo rating of chess engine</p>

In [12]:
print(games.loc[games["BlackElo"].idxmax()])
print((games["WhiteElo"] >= 3000).sum())
print((games["BlackElo"] >= 3000).sum())
games=games[(games["BlackElo"] < 3000) & (games["WhiteElo"] < 3000)]
print(len(games))
print(games.loc[games["BlackElo"].idxmax()])

Event                                         TCh-BEL 2014-15
Site                                              Belgium BEL
Date                                               2014.09.28
White                                               Claesen,P
Black                                              Decoster,F
Result                                                1/2-1/2
WhiteElo                                               2327.0
BlackElo                                             204269.0
ECO                                                       B20
Opening                                      Sicilian defence
Moves       1. e4 c5 2. c4 Nc6 3. Nc3 e6 4. g3 g6 5. Bg2 B...
Name: 294391, dtype: object
4299
4300
3255883
Event                                7th Sinquefield Cup 2019
Site                                          Saint Louis USA
Date                                               2019.08.26
White                                               Aronian,L
Black                                               Carlsen,M
Result                                                1/2-1/2
WhiteElo                                               2765.0
BlackElo                                               2882.0
ECO                                                       B31
Opening                                              Sicilian
Moves       1. e4 c5 2. Nf3 Nc6 3. Bb5 g6 4. c3 Nf6 5. Qe2...
Name: 1059632, dtype: object

Converting the Date column to Datetime

In [13]:
games["Date"] = pd.to_datetime(games["Date"], format="%Y.%m.%d", errors="coerce")
print(games.isna().sum())
games=games[games["Date"].notna()]
games=games.sort_values("Date").reset_index(drop=True)

Event         0
Site          0
Date        126
White         0
Black         0
Result        0
WhiteElo      0
BlackElo      0
ECO           0
Opening       0
Moves         0
dtype: int64

Clening the Results Column

In [14]:
games["Result"].value_counts()

Result
1-0        1365354
0-1        1139501
1/2-1/2     750835
*               36
+/-             10
-/+              7
-                5
0-0              3
1-0 ff           2
(+)-(-)          1
1/2 1/2          1
1-O              1
00-1             1
Name: count, dtype: int64

In [15]:
games["Result"] = games["Result"].replace("1/2 1/2", "1/2-1/2").replace("1-O", "1-0").replace("00-1", "0-1")
valid_results=["1-0", "0-1", "1/2-1/2"]
games = games[games["Result"].isin(valid_results)]
games["Result"].value_counts()

Result
1-0        1365355
0-1        1139502
1/2-1/2     750836
Name: count, dtype: int64

In [16]:
games["Result"] = games["Result"].map({"1-0": 1, "1/2-1/2": 0.5, "0-1": 0})
games["Result"].value_counts()

Result
1.0    1365355
0.0    1139502
0.5     750836
Name: count, dtype: int64

Final check

In [17]:
print(games.shape)

print(games.isna().sum())

print(games[games.duplicated()])
games = games.drop_duplicates()
print(games.duplicated().sum())

print(games["Result"].value_counts())

print(games.describe())

(3255693, 11)
Event       0
Site        0
Date        0
White       0
Black       0
Result      0
WhiteElo    0
BlackElo    0
ECO         0
Opening     0
Moves       0
dtype: int64
                     Event          Site       Date        White      Black  \
738391  Varennes Open 2017  Montreal CAN 2017-10-07  Hambleton,A  Morella,J

        Result  WhiteElo  BlackElo  ECO       Opening  \
738391     1.0    2479.0    2248.0  A04  Reti opening

                                                    Moves
738391  1. Nf3 c5 2. c4 Nc6 3. Nc3 g6 4. d4 cxd4 5. Nx...
0
Result
1.0    1365354
0.0    1139502
0.5     750836
Name: count, dtype: int64
                             Date        Result      WhiteElo      BlackElo
count                     3255692  3.255692e+06  3.255692e+06  3.255692e+06
mean   2021-02-08 04:52:21.018499  5.346857e-01  2.246864e+03  2.243631e+03
min           2012-06-02 00:00:00  0.000000e+00  1.001000e+03  1.001000e+03
25%           2018-03-25 00:00:00  0.000000e+00  2.092000e+03  2.089000e+03
50%           2022-01-27 00:00:00  5.000000e-01  2.279000e+03  2.276000e+03
75%           2024-05-14 00:00:00  1.000000e+00  2.435000e+03  2.433000e+03
max           2026-06-08 00:00:00  1.000000e+00  2.882000e+03  2.882000e+03
std                           NaN  4.371971e-01  2.737051e+02  2.745516e+02

Converting the Dataframe to .csv

In [18]:
games.info(memory_usage="deep")
games.drop(columns=["Moves"],inplace=True)
games.info()

<class 'pandas.DataFrame'>
Index: 3255692 entries, 0 to 3255756
Data columns (total 11 columns):
 #   Column    Dtype
---  ------    -----
 0   Event     str
 1   Site      str
 2   Date      datetime64[us]
 3   White     str
 4   Black     str
 5   Result    float64
 6   WhiteElo  float64
 7   BlackElo  float64
 8   ECO       str
 9   Opening   str
 10  Moves     str
dtypes: datetime64[us](1), float64(3), str(7)
memory usage: 3.1 GB
<class 'pandas.DataFrame'>
Index: 3255692 entries, 0 to 3255756
Data columns (total 10 columns):
 #   Column    Dtype
---  ------    -----
 0   Event     str
 1   Site      str
 2   Date      datetime64[us]
 3   White     str
 4   Black     str
 5   Result    float64
 6   WhiteElo  float64
 7   BlackElo  float64
 8   ECO       str
 9   Opening   str
dtypes: datetime64[us](1), float64(3), str(6)
memory usage: 273.2 MB

In [ ]:
games.to_csv(os.path.join(project_dir, "data/cleaned_chess.csv"), index=False)

In [20]:
new=pd.read_csv(os.path.join(project_dir, "data/cleaned_chess.csv"))
len(new)

3255692