## Training the Final Chess Data with DecisionTree, RandomForest and XGBoost

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
from scipy.stats import randint

#### Loading the Data

In [3]:
project_dir = os.path.dirname(os.getcwd())
games = pd.read_csv(os.path.join(project_dir,"data/final_chess.csv"), parse_dates=["Date"])

In [4]:
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 3255656 entries, 0 to 3255655
Data columns (total 98 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Site                    str
 1   Date                    datetime64[us]
 2   White                   str
 3   Black                   str
 4   Result                  float64
 5   WhiteElo                float64
 6   BlackElo                float64
 7   ECO                     str
 8   EloDiff                 float64
 9   absEloDiff              float64
 10  AvgElo                  float64
 11  HigherRatedPlayer       int64
 12  WhiteGames              int64
 13  WhiteWin                int64
 14  WhiteLoss               int64
 15  WhiteDraw               int64
 16  BlackGames              int64
 17  BlackWin                int64
 18  BlackLoss               int64
 19  BlackDraw               int64
 20  WhiteWinRate            float64
 21  WhiteLossRate           float64
 22  WhiteDrawRate           float64
 23  BlackWinRate            float64
 24  BlackLossRate           float64
 25  BlackDrawRate           float64
 26  WLast10                 float64
 27  BLast10                 float64
 28  WasWGames               int64
 29  WasWWin                 int64
 30  WasWLoss                int64
 31  WasWDraw                int64
 32  WasBGames               int64
 33  WasBWin                 int64
 34  WasBLoss                int64
 35  WasBDraw                int64
 36  BasWGames               int64
 37  BasWWin                 int64
 38  BasWLoss                int64
 39  BasWDraw                int64
 40  BasBGames               int64
 41  BasBWin                 int64
 42  BasBLoss                int64
 43  BasBDraw                int64
 44  WasWWinRate             float64
 45  WasWLossRate            float64
 46  WasWDrawRate            float64
 47  WasBWinRate             float64
 48  WasBLossRate            float64
 49  WasBDrawRate            float64
 50  BasWWinRate             float64
 51  BasWLossRate            float64
 52  BasWDrawRate            float64
 53  BasBWinRate             float64
 54  BasBLossRate            float64
 55  BasBDrawRate            float64
 56  h2h_games               int64
 57  h2h_Player1Win          int64
 58  h2h_Player2Win          int64
 59  h2h_Draw                int64
 60  h2h_Player1WinRate      float64
 61  h2h_Player2WinRate      float64
 62  h2h_DrawRate            float64
 63  h2h_last5               float64
 64  h2h_last5P1win          float64
 65  h2h_last5P2win          float64
 66  h2h_last5draw           float64
 67  h2h_P1winStreak         int64
 68  h2h_P2winStreak         int64
 69  h2h_DrawStreak          int64
 70  WhiteDaysSinceLastGame  int64
 71  BlackDaysSinceLastGame  int64
 72  Last10Diff              float64
 73  GamesDiff               int64
 74  WinDiff                 int64
 75  WinRateDiff             float64
 76  h2h_WinDiff             int64
 77  h2h_WinRateDiff         float64
 78  DaysSinceLastGameDiff   int64
 79  ECO_Games               int64
 80  ECO_WhiteWin            int64
 81  ECO_BlackWin            int64
 82  ECO_Draw                int64
 83  ECO_WhiteWinRate        float64
 84  ECO_BlackWinRate        float64
 85  ECO_DrawRate            float64
 86  WLast10win              float64
 87  WLast10draw             float64
 88  WLast10loss             float64
 89  BLast10win              float64
 90  BLast10draw             float64
 91  BLast10loss             float64
 92  WhiteWinStreak          int64
 93  WhiteLossStreak         int64
 94  WhiteDrawStreak         int64
 95  BlackWinStreak          int64
 96  BlackLossStreak         int64
 97  BlackDrawStreak         int64
dtypes: datetime64[us](1), float64(45), int64(48), str(4)
memory usage: 2.4 GB

#### Preparing Data for Training

In [ ]:
X = games.drop(columns=[
    "White", "Black", "Result", "Site", "ECO",

    # White/Black color counts
    'WasBWinRate', 'WasBLossRate', 'WasBDrawRate', 'BasWWinRate', 'BasWLossRate', 'BasWDrawRate',
    "WasBGames", "WasBWin", "WasBLoss", "WasBDraw",
    "BasWGames", "BasWWin", "BasWLoss", "BasWDraw",
])
y = games["Result"].map({1: 2, 0.5: 1, 0:0}) #sklearn only considers integers 

"""
0 = Black win
1 = Draw
2 = White win
"""

'\n0 = Black win\n1 = Draw\n2 = White win\n'

In [6]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 3255656 entries, 0 to 3255655
Data columns (total 79 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Date                    datetime64[us]
 1   WhiteElo                float64
 2   BlackElo                float64
 3   EloDiff                 float64
 4   absEloDiff              float64
 5   AvgElo                  float64
 6   HigherRatedPlayer       int64
 7   WhiteGames              int64
 8   WhiteWin                int64
 9   WhiteLoss               int64
 10  WhiteDraw               int64
 11  BlackGames              int64
 12  BlackWin                int64
 13  BlackLoss               int64
 14  BlackDraw               int64
 15  WhiteWinRate            float64
 16  WhiteLossRate           float64
 17  WhiteDrawRate           float64
 18  BlackWinRate            float64
 19  BlackLossRate           float64
 20  BlackDrawRate           float64
 21  WLast10                 float64
 22  BLast10                 float64
 23  WasWGames               int64
 24  WasWWin                 int64
 25  WasWLoss                int64
 26  WasWDraw                int64
 27  BasBGames               int64
 28  BasBWin                 int64
 29  BasBLoss                int64
 30  BasBDraw                int64
 31  WasWWinRate             float64
 32  WasWLossRate            float64
 33  WasWDrawRate            float64
 34  BasBWinRate             float64
 35  BasBLossRate            float64
 36  BasBDrawRate            float64
 37  h2h_games               int64
 38  h2h_Player1Win          int64
 39  h2h_Player2Win          int64
 40  h2h_Draw                int64
 41  h2h_Player1WinRate      float64
 42  h2h_Player2WinRate      float64
 43  h2h_DrawRate            float64
 44  h2h_last5               float64
 45  h2h_last5P1win          float64
 46  h2h_last5P2win          float64
 47  h2h_last5draw           float64
 48  h2h_P1winStreak         int64
 49  h2h_P2winStreak         int64
 50  h2h_DrawStreak          int64
 51  WhiteDaysSinceLastGame  int64
 52  BlackDaysSinceLastGame  int64
 53  Last10Diff              float64
 54  GamesDiff               int64
 55  WinDiff                 int64
 56  WinRateDiff             float64
 57  h2h_WinDiff             int64
 58  h2h_WinRateDiff         float64
 59  DaysSinceLastGameDiff   int64
 60  ECO_Games               int64
 61  ECO_WhiteWin            int64
 62  ECO_BlackWin            int64
 63  ECO_Draw                int64
 64  ECO_WhiteWinRate        float64
 65  ECO_BlackWinRate        float64
 66  ECO_DrawRate            float64
 67  WLast10win              float64
 68  WLast10draw             float64
 69  WLast10loss             float64
 70  BLast10win              float64
 71  BLast10draw             float64
 72  BLast10loss             float64
 73  WhiteWinStreak          int64
 74  WhiteLossStreak         int64
 75  WhiteDrawStreak         int64
 76  BlackWinStreak          int64
 77  BlackLossStreak         int64
 78  BlackDrawStreak         int64
dtypes: datetime64[us](1), float64(38), int64(40)
memory usage: 1.9 GB

In [6]:
n = len(games)
s1 = int(0.7 * n)
s2 = int(0.85 * n)

In [7]:
X_train = X.iloc[:s1].drop(columns=["Date"])
y_train = y.iloc[:s1].drop(columns=["Date"])
X_val = X.iloc[s1:s2].drop(columns=["Date"])
y_val = y.iloc[s1:s2].drop(columns=["Date"])
X_test = X.iloc[s2:].drop(columns=["Date"])
y_test = y.iloc[s2:].drop(columns=["Date"])

### Decision Tree

In [9]:
from sklearn.tree import DecisionTreeClassifier

#### RandomizedSearch

In [21]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import TimeSeriesSplit

In [51]:
indices = np.arange(0, n)
sample_indices = np.random.choice(indices, size=500000, replace=False)
X_srch = X.iloc[sample_indices]
y_srch = y.iloc[sample_indices]

In [26]:
tscv = TimeSeriesSplit(5)

In [27]:
param_grid = {
    "max_depth": [10, 20, 30, 40, 60, 80, 100, None],
    "min_samples_split": np.arange(2,500),
    "min_samples_leaf": np.arange(1,200),
    "max_features": [None, "sqrt", 0.7],
    "max_leaf_nodes": [None, 100, 250, 500, 750, 1000],
    "class_weight": [None, "balanced"],
    "ccp_alpha": [0.0, 1e-5, 1e-4, 1e-3]
}

In [40]:
random_search = RandomizedSearchCV(DecisionTreeClassifier(criterion="gini", random_state=67), param_grid, n_iter=100, scoring="accuracy", cv=tscv, n_jobs=4, random_state=67)

In [ ]:
random_search.fit(X_srch, y_srch)

/Users/vallurileelasaikrishna/Documents/chess/.venv/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

RandomizedSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
                   estimator=DecisionTreeClassifier(random_state=67),
                   n_iter=100, n_jobs=4,
                   param_distributions={'ccp_alpha': [0.0, 1e-05, 0.0001,
                                                      0.001],
                                        'class_weight': [None, 'balanced'],
                                        'max_depth': [10, 20, 30, 40, 60, 80,
                                                      100, None],
                                        'max_features': [None, 'sqrt', 0.7],
                                        'max_leaf_nodes': [None, 1...
       418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430,
       431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443,
       444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456,
       457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469,
       470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482,
       483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495,
       496, 497, 498, 499])},
                   random_state=67, scoring='accuracy')

In [ ]:
random_search.best_score_

np.float64(0.5902055608222433)

In [ ]:
results = pd.DataFrame(random_search.cv_results_)
results.head()

#### On actual Data

In [9]:
s3 = int(0.3 * n)
s4 = int(0.75 * n)
s5 = int(0.9 * n)
X_ntrain = X.iloc[s3:s4]
y_ntrain = y.iloc[s3:s4]
X_nval = X.iloc[s4:s5]
y_nval = y.iloc[s4:s5]

In [7]:
Xtrain = X[(X["Date"].dt.year >= 2016) & (X["Date"].dt.year <= 2024)].drop(columns="Date")
ytrain = y[(X["Date"].dt.year >= 2016) & (X["Date"].dt.year <= 2024)].drop(columns="Date")
Xval   = X[X["Date"].dt.year == 2025].drop(columns="Date")
yval   = y[X["Date"].dt.year == 2025].drop(columns="Date")
Xtest  = X[X["Date"].dt.year == 2026].drop(columns="Date")
ytest  = y[X["Date"].dt.year == 2026].drop(columns="Date")

In [10]:
#parameters from the randomized search

dtc = DecisionTreeClassifier(ccp_alpha=1e-05, class_weight={
    0: 1.0,
    1: 1.5,
    2: 1.0
}, max_depth=20,
                       max_leaf_nodes=1000, min_samples_leaf=168,
                       min_samples_split=654, random_state=67)

In [11]:
dtc.fit(Xtrain, ytrain)

DecisionTreeClassifier(ccp_alpha=1e-05, class_weight={0: 1.0, 1: 1.5, 2: 1.0},
                       max_depth=20, max_leaf_nodes=1000, min_samples_leaf=168,
                       min_samples_split=654, random_state=67)

In [12]:
y_pred = dtc.predict(Xval)

In [13]:
# accuracy
np.mean(y_pred==yval)

np.float64(0.6016069181889124)

In [14]:
confusion_matrix(yval, y_pred)

array([[ 86687,  18167,  33894],
       [ 19820,  30394,  23747],
       [ 34669,  19796, 109572]])

In [15]:
classification_report(yval, y_pred).splitlines()

['              precision    recall  f1-score   support',
 '',
 '           0       0.61      0.62      0.62    138748',
 '           1       0.44      0.41      0.43     73961',
 '           2       0.66      0.67      0.66    164037',
 '',
 '    accuracy                           0.60    376746',
 '   macro avg       0.57      0.57      0.57    376746',
 'weighted avg       0.60      0.60      0.60    376746']

In [39]:
pd.DataFrame(dtc.feature_importances_, index=Xtrain.columns).sort_values(by=0).tail(45)

                               0
GamesDiff               0.000094
BasBWin                 0.000110
BasBLoss                0.000117
h2h_Draw                0.000124
WLast10loss             0.000226
BasBDraw                0.000241
WhiteWinRate            0.000246
BlackDrawStreak         0.000288
WhiteLossStreak         0.000308
WhiteDraw               0.000391
BasBWinRate             0.000398
WasWDrawRate            0.000446
WasWDraw                0.000465
BlackLossStreak         0.000537
WhiteElo                0.000545
BlackDraw               0.000576
BlackWinStreak          0.000619
WhiteWin                0.000650
BlackElo                0.000687
BlackWinRate            0.000753
h2h_DrawRate            0.000798
WhiteWinStreak          0.000882
BasBDrawRate            0.001127
WasWLoss                0.001273
BLast10loss             0.001449
WinDiff                 0.001511
BlackWin                0.001771
BlackLoss               0.001796
WhiteGames              0.001870
WhiteLoss               0.001976
DaysSinceLastGameDiff   0.002269
ECO_BlackWinRate        0.002801
BlackLossRate           0.004474
WhiteLossRate           0.004834
ECO_DrawRate            0.004933
WasWLossRate            0.005772
WLast10draw             0.010871
BLast10draw             0.015258
WinRateDiff             0.037158
BlackDrawRate           0.044938
WhiteDaysSinceLastGame  0.051982
BlackDaysSinceLastGame  0.070620
absEloDiff              0.134070
WhiteDrawRate           0.158900
EloDiff                 0.428666

saving the model in results

In [ ]:
#joblib.dump(dtc, os.path.join(project_dir, "results/models/dtc_60.03.joblib"))

['/Users/vallurileelasaikrishna/Documents/chess/results/models/dtc_60.03.joblib']

### Random Forest

#### Randomized search for rfc

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import TimeSeriesSplit

In [52]:
tscv = TimeSeriesSplit(3)

In [53]:
param_grid = {
    "n_estimators" : randint(99, 699),
    "max_depth" : [20, 30, 40, 50, 60, None],
    "min_samples_split" : randint(250, 700),
    "min_samples_leaf" : randint(51, 400),
    "max_features" : [None, "sqrt", 0.7],
    "class_weight" : [None, "balanced"],
    "ccp_alpha" : [0, 1e-05]
}

In [54]:
random_search = RandomizedSearchCV(RandomForestClassifier(bootstrap=True, random_state=67, n_jobs=-1, oob_score=True),
                                   param_distributions=param_grid,
                                   n_iter=20,
                                   cv=tscv,
                                   random_state=67,
                                   n_jobs=-1,
                                   scoring="accuracy",
                                   return_train_score=True,
                                   verbose=2
                                   )

In [55]:
random_search.fit(X_srch, y_srch)

Fitting 3 folds for each of 20 candidates, totalling 60 fits
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=sqrt, min_samples_leaf=349, min_samples_split=692, n_estimators=125; total time= 1.3min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=sqrt, min_samples_leaf=349, min_samples_split=692, n_estimators=125; total time= 3.0min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=sqrt, min_samples_leaf=349, min_samples_split=692, n_estimators=125; total time= 5.2min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=40, max_features=sqrt, min_samples_leaf=58, min_samples_split=643, n_estimators=646; total time= 7.4min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=60, max_features=0.7, min_samples_leaf=225, min_samples_split=675, n_estimators=249; total time=10.3min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=None, min_samples_leaf=214, min_samples_split=344, n_estimators=281; total time=16.2min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=40, max_features=sqrt, min_samples_leaf=58, min_samples_split=643, n_estimators=646; total time=17.9min
[CV] END ccp_alpha=0, class_weight=None, max_depth=50, max_features=sqrt, min_samples_leaf=103, min_samples_split=632, n_estimators=289; total time= 2.4min
[CV] END ccp_alpha=0, class_weight=None, max_depth=50, max_features=sqrt, min_samples_leaf=103, min_samples_split=632, n_estimators=289; total time= 5.5min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=20, max_features=0.7, min_samples_leaf=90, min_samples_split=540, n_estimators=581; total time=25.2min
[CV] END ccp_alpha=0, class_weight=None, max_depth=50, max_features=sqrt, min_samples_leaf=103, min_samples_split=632, n_estimators=289; total time= 9.2min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=40, max_features=sqrt, min_samples_leaf=58, min_samples_split=643, n_estimators=646; total time=30.5min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=60, max_features=0.7, min_samples_leaf=225, min_samples_split=675, n_estimators=249; total time=24.3min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=None, min_samples_leaf=214, min_samples_split=344, n_estimators=281; total time=40.4min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=20, max_features=None, min_samples_leaf=141, min_samples_split=406, n_estimators=186; total time=13.7min
[CV] END ccp_alpha=0, class_weight=None, max_depth=40, max_features=0.7, min_samples_leaf=206, min_samples_split=417, n_estimators=559; total time=25.0min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=30, max_features=sqrt, min_samples_leaf=121, min_samples_split=552, n_estimators=356; total time= 5.4min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=60, max_features=0.7, min_samples_leaf=225, min_samples_split=675, n_estimators=249; total time=43.9min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=30, max_features=sqrt, min_samples_leaf=121, min_samples_split=552, n_estimators=356; total time=11.5min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=20, max_features=None, min_samples_leaf=141, min_samples_split=406, n_estimators=186; total time=30.6min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=20, max_features=0.7, min_samples_leaf=90, min_samples_split=540, n_estimators=581; total time=64.1min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=30, max_features=sqrt, min_samples_leaf=121, min_samples_split=552, n_estimators=356; total time=17.4min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=None, min_samples_leaf=214, min_samples_split=344, n_estimators=281; total time=68.1min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=30, max_features=0.7, min_samples_leaf=328, min_samples_split=343, n_estimators=197; total time= 9.8min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=50, max_features=None, min_samples_leaf=344, min_samples_split=458, n_estimators=286; total time=16.8min
[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=20, max_features=0.7, min_samples_leaf=74, min_samples_split=406, n_estimators=121; total time= 6.8min
[CV] END ccp_alpha=0, class_weight=None, max_depth=40, max_features=0.7, min_samples_leaf=206, min_samples_split=417, n_estimators=559; total time=58.7min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=30, max_features=0.7, min_samples_leaf=328, min_samples_split=343, n_estimators=197; total time=22.7min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=20, max_features=None, min_samples_leaf=141, min_samples_split=406, n_estimators=186; total time=50.5min
[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=20, max_features=0.7, min_samples_leaf=74, min_samples_split=406, n_estimators=121; total time=15.1min

/Users/vallurileelasaikrishna/Documents/chess/.venv/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=40, max_features=None, min_samples_leaf=381, min_samples_split=295, n_estimators=212; total time=12.5min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=50, max_features=None, min_samples_leaf=344, min_samples_split=458, n_estimators=286; total time=41.5min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=30, max_features=0.7, min_samples_leaf=328, min_samples_split=343, n_estimators=197; total time=36.0min
[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=20, max_features=0.7, min_samples_leaf=74, min_samples_split=406, n_estimators=121; total time=23.4min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=20, max_features=0.7, min_samples_leaf=90, min_samples_split=540, n_estimators=581; total time=110.0min
[CV] END ccp_alpha=0, class_weight=None, max_depth=20, max_features=0.7, min_samples_leaf=295, min_samples_split=436, n_estimators=211; total time= 9.1min
[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=40, max_features=None, min_samples_leaf=381, min_samples_split=295, n_estimators=212; total time=28.8min
[CV] END ccp_alpha=0, class_weight=None, max_depth=30, max_features=0.7, min_samples_leaf=168, min_samples_split=427, n_estimators=224; total time=10.2min
[CV] END ccp_alpha=0, class_weight=None, max_depth=40, max_features=0.7, min_samples_leaf=206, min_samples_split=417, n_estimators=559; total time=95.6min
[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=20, max_features=None, min_samples_leaf=202, min_samples_split=667, n_estimators=544; total time=32.2min
[CV] END ccp_alpha=0, class_weight=None, max_depth=20, max_features=0.7, min_samples_leaf=295, min_samples_split=436, n_estimators=211; total time=21.1min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=0.7, min_samples_leaf=239, min_samples_split=569, n_estimators=130; total time= 5.6min
[CV] END ccp_alpha=1e-05, class_weight=balanced, max_depth=50, max_features=None, min_samples_leaf=344, min_samples_split=458, n_estimators=286; total time=68.1min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=50, max_features=0.7, min_samples_leaf=137, min_samples_split=532, n_estimators=153; total time= 8.0min
[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=40, max_features=None, min_samples_leaf=381, min_samples_split=295, n_estimators=212; total time=46.9min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=0.7, min_samples_leaf=239, min_samples_split=569, n_estimators=130; total time=14.1min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=50, max_features=sqrt, min_samples_leaf=284, min_samples_split=526, n_estimators=358; total time= 5.0min
[CV] END ccp_alpha=0, class_weight=None, max_depth=30, max_features=0.7, min_samples_leaf=168, min_samples_split=427, n_estimators=224; total time=23.8min
[CV] END ccp_alpha=0, class_weight=None, max_depth=20, max_features=0.7, min_samples_leaf=295, min_samples_split=436, n_estimators=211; total time=34.5min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=50, max_features=0.7, min_samples_leaf=137, min_samples_split=532, n_estimators=153; total time=17.9min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=50, max_features=sqrt, min_samples_leaf=284, min_samples_split=526, n_estimators=358; total time=10.7min
[CV] END ccp_alpha=0, class_weight=None, max_depth=60, max_features=0.7, min_samples_leaf=110, min_samples_split=691, n_estimators=148; total time= 5.8min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=None, max_features=0.7, min_samples_leaf=239, min_samples_split=569, n_estimators=130; total time=22.9min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=50, max_features=sqrt, min_samples_leaf=284, min_samples_split=526, n_estimators=358; total time=14.4min
[CV] END ccp_alpha=0, class_weight=None, max_depth=30, max_features=0.7, min_samples_leaf=168, min_samples_split=427, n_estimators=224; total time=34.8min
[CV] END ccp_alpha=0, class_weight=None, max_depth=60, max_features=0.7, min_samples_leaf=110, min_samples_split=691, n_estimators=148; total time=10.8min
[CV] END ccp_alpha=0, class_weight=balanced, max_depth=50, max_features=0.7, min_samples_leaf=137, min_samples_split=532, n_estimators=153; total time=22.6min
[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=20, max_features=None, min_samples_leaf=202, min_samples_split=667, n_estimators=544; total time=64.9min
[CV] END ccp_alpha=0, class_weight=None, max_depth=60, max_features=0.7, min_samples_leaf=110, min_samples_split=691, n_estimators=148; total time=13.1min
[CV] END ccp_alpha=1e-05, class_weight=None, max_depth=20, max_features=None, min_samples_leaf=202, min_samples_split=667, n_estimators=544; total time=65.9min

RandomizedSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                   estimator=RandomForestClassifier(n_jobs=-1, oob_score=True,
                                                    random_state=67),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'ccp_alpha': [0, 1e-05],
                                        'class_weight': [None, 'balanced'],
                                        'max_depth': [20, 30, 40, 50, 60, None],
                                        'max_features': [None, 'sqrt', 0.7],
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11d28e110>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11d22ba90>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x120b7c810>},
                   random_state=67, return_train_score=True, scoring='accuracy',
                   verbose=2)

In [56]:
random_search.best_score_

np.float64(0.5995946666666667)

In [57]:
results = pd.DataFrame(random_search.cv_results_)
results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_ccp_alpha,param_class_weight,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,...,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,mean_train_score,std_train_score
0,1106.191842,567.446399,9.253906,0.539031,0.00001,balanced,40,sqrt,58,643,...,0.585832,0.585864,0.584717,0.001599,9,0.592984,0.594180,0.595101,0.594088,0.000867
1,2489.222211,1272.579373,4.711960,0.960052,0.00000,balanced,None,None,214,344,...,0.584368,0.584184,0.582387,0.002673,19,0.593688,0.594544,0.595901,0.594711,0.000911
2,188.027809,94.336632,1.563711,0.121787,0.00000,balanced,None,sqrt,349,692,...,0.584208,0.583632,0.582835,0.001553,15,0.587296,0.589096,0.589664,0.588685,0.001009
3,3977.119808,2077.499409,8.453291,0.897590,0.00001,balanced,20,0.7,90,540,...,0.585584,0.585080,0.583589,0.002473,12,0.595416,0.596460,0.597939,0.596605,0.001035
4,1567.548978,825.357511,3.296046,0.448132,0.00000,balanced,60,0.7,225,675,...,0.584104,0.584480,0.582467,0.002586,17,0.589976,0.590960,0.592008,0.590981,0.000830

#### On actual data

In [20]:
rfc = RandomForestClassifier(ccp_alpha=1e-05, max_depth=20, max_features=0.7,
                       min_samples_leaf=74, min_samples_split=406,
                       n_estimators=121, n_jobs=-1, oob_score=True,
                       random_state=67)

In [21]:
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 1e-05,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 20,
 'max_features': 0.7,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 74,
 'min_samples_split': 406,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 121,
 'n_jobs': -1,
 'oob_score': True,
 'random_state': 67,
 'verbose': 0,
 'warm_start': False}

In [23]:
rfc.fit(Xtrain, ytrain)

RandomForestClassifier(ccp_alpha=1e-05, max_depth=20, max_features=0.7,
                       min_samples_leaf=74, min_samples_split=406,
                       n_estimators=121, n_jobs=-1, oob_score=True,
                       random_state=67)

In [24]:
rfc.oob_score_

0.5997278837375793

In [25]:
y_pred = rfc.predict(Xval)

In [26]:
np.mean(y_pred==yval) # accuracy

np.float64(0.6102599629458574)

In [27]:
confusion_matrix(yval, y_pred)

array([[ 93967,   7090,  37691],
       [ 26189,  16703,  31069],
       [ 37373,   7421, 119243]])

In [28]:
classification_report(yval, y_pred).splitlines()

['              precision    recall  f1-score   support',
 '',
 '           0       0.60      0.68      0.63    138748',
 '           1       0.54      0.23      0.32     73961',
 '           2       0.63      0.73      0.68    164037',
 '',
 '    accuracy                           0.61    376746',
 '   macro avg       0.59      0.54      0.54    376746',
 'weighted avg       0.60      0.61      0.59    376746']

In [31]:
pd.DataFrame(rfc.feature_importances_, index=X.columns).sort_values(by=0).tail(42)

ValueError: Shape of passed values is (78, 1), indices imply (79, 1)

saving the model

In [ ]:
#joblib.dump(rfc, os.path.join(project_dir, "results/models/rfc_61.18.joblib"))

['/Users/vallurileelasaikrishna/Documents/chess/results/models/rfc_61.18.joblib']